version: '3.5'

services:

  app:
    image: node:10.15-alpine
    container_name: app
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=local
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
    volumes:
      - .:/src/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
    working_dir: /src/app
    command: yarn start

  postgres:
    image: postgres:11.1-alpine
    environment:
      - POSTGRES_DB=local
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  postgres-admin:
    image: sosedoff/pgweb
    environment:
      - DATABASE_URL=postgres://local:local@postgres:5432/local?sslmode=disable
    ports:
      - 8080:8081
    depends_on:
      - postgres
