type Poll {
  id: Int
  title: String
  choices: [Choice]
  choice(id: Int): Choice
  creator: User
}

type Choice {
  id: Int
  title: String
  point: Int
}

type Query {
  poll(id: Int): Poll
  polls: [Poll]
}

type Mutation {
  createPoll(
    title: String!
    creatorId: Int!
  ): Poll
  createChoice(
    pollId: Int!
    title: String!
  ): Choice
  votePoll(
    id: Int!
    choice: Int!
  ): Choice
}
